import type { EditorSlide } from "./types";

const sans = "var(--font-geist-sans), system-ui, sans-serif";

export const INITIAL_SLIDES: EditorSlide[] = [
  {
    id: "es-1",
    padding: 48,
    spacing: 16,
    align: "left",
    elements: [
      {
        type: "text",
        id: "e1-t",
        role: "Title",
        content: "Q3 narrative",
        x: 8,
        y: 12,
        w: 72,
        h: 14,
        locked: true,
        fontFamily: sans,
        fontSize: 36,
        lineHeight: 1.15,
        align: "left",
      },
      {
        type: "text",
        id: "e1-s",
        role: "Subtitle",
        content: "Growth, risk, and next steps",
        x: 8,
        y: 28,
        w: 64,
        h: 10,
        locked: false,
        fontFamily: sans,
        fontSize: 18,
        lineHeight: 1.4,
        align: "left",
      },
      {
        type: "text",
        id: "e1-b",
        role: "Body",
        content: "• North star metric holding\n• Pipeline weighted to enterprise\n• Hiring on track for backend",
        x: 8,
        y: 42,
        w: 52,
        h: 38,
        locked: false,
        fontFamily: sans,
        fontSize: 15,
        lineHeight: 1.45,
        align: "left",
      },
      {
        type: "placeholder",
        id: "e1-img",
        role: "Hero image",
        placeholderKind: "image",
        label: "Image",
        x: 64,
        y: 18,
        w: 30,
        h: 62,
        locked: true,
      },
    ],
  },
  {
    id: "es-2",
    padding: 40,
    spacing: 12,
    align: "left",
    elements: [
      {
        type: "text",
        id: "e2-t",
        role: "Title",
        content: "Risks & mitigations",
        x: 8,
        y: 10,
        w: 80,
        h: 12,
        locked: true,
        fontFamily: sans,
        fontSize: 28,
        lineHeight: 1.2,
        align: "left",
      },
      {
        type: "text",
        id: "e2-b",
        role: "Body",
        content: "Vendor concentration — dual-source critical APIs by Oct.\nCompliance review — legal sign-off scheduled.\nKey person — document runbooks this sprint.",
        x: 8,
        y: 26,
        w: 70,
        h: 50,
        locked: false,
        fontFamily: sans,
        fontSize: 14,
        lineHeight: 1.5,
        align: "left",
      },
    ],
  },
  {
    id: "es-3",
    padding: 56,
    spacing: 20,
    align: "center",
    elements: [
      {
        type: "text",
        id: "e3-t",
        role: "Title",
        content: "Thank you",
        x: 15,
        y: 38,
        w: 70,
        h: 16,
        locked: true,
        fontFamily: sans,
        fontSize: 40,
        lineHeight: 1.1,
        align: "center",
      },
      {
        type: "text",
        id: "e3-s",
        role: "Subtitle",
        content: "name@company.com",
        x: 20,
        y: 56,
        w: 60,
        h: 10,
        locked: false,
        fontFamily: sans,
        fontSize: 16,
        lineHeight: 1.35,
        align: "center",
      },
    ],
  },
];
